/*


USE [master]
GO

/****** Object:  Database [sqlders]    Script Date: 6.12.2020 21:46:57 ******/
DROP DATABASE [sqlders]
GO

/****** Object:  Database [sqlders]    Script Date: 6.12.2020 21:46:57 ******/
CREATE DATABASE [sqlders] ON  PRIMARY 
( NAME = N'sqlders', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\sqlders.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sqlders_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\sqlders_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sqlders].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sqlders] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sqlders] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sqlders] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sqlders] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sqlders] SET ARITHABORT OFF 
GO

ALTER DATABASE [sqlders] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sqlders] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sqlders] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sqlders] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sqlders] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sqlders] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sqlders] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sqlders] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sqlders] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sqlders] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sqlders] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sqlders] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sqlders] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sqlders] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sqlders] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sqlders] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sqlders] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sqlders] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sqlders] SET  MULTI_USER 
GO

ALTER DATABASE [sqlders] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sqlders] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sqlders] SET  READ_WRITE 
GO







*/


CREATE TABLE SATICI(
SATICIID INTEGER IDENTITY(1,1) NOT NULL,
SATICIADI VARCHAR(20) NOT NULL,
SATICISOYADI VARCHAR(20) NOT NULL,
SATICITELEFON VARCHAR(11) NOT NULL
PRIMARY KEY CLUSTERED 
 (
	SATICIID ASC
 )WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
)ON [PRIMARY]


CREATE TABLE URUN(
URUNID INTEGER IDENTITY(1,1) NOT NULL,
URUNKODU VARCHAR(20) NOT NULL,
URUNADI VARCHAR(20) NOT NULL,
URUNFÝYATI MONEY,
PRIMARY KEY CLUSTERED 
 (
	URUNID ASC
 ) WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
) ON [PRIMARY]




CREATE TABLE SIPARIS(
SIPARISID INTEGER IDENTITY(1,1) NOT NULL,
MUSTERIID INTEGER,
SIPARISTARIH VARCHAR(10),
SIPARISDURUM VARCHAR(20),
URUNID INTEGER,
SATICIID INTEGER,
PRIMARY KEY CLUSTERED 
 (
	SIPARISID ASC
 ) WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
) ON [PRIMARY]



CREATE TABLE ADRES(
ADRESID INTEGER IDENTITY(1,1),
MusterýID INTEGER,
ADRESULKE VARCHAR(25) NOT NULL,
ADRESIL VARCHAR(25) NOT NULL,
ADRESILCE VARCHAR(25)NOT NULL,
ADRESYORUM VARCHAR(100) NOT NULL
PRIMARY KEY CLUSTERED 
 (
	ADRESID ASC
 )  WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY] 
)ON [PRIMARY]


CREATE TABLE MUSTERILER(
MUSTERIID INT IDENTITY(1,1) NOT NULL,
MUSTERIAD VARCHAR(20) NOT NULL,
MUSTERISOYAD VARCHAR(20) NOT NULL,
MUSTERICINSIYET VARCHAR(1) NOT NULL,
MUSTERITELEFON VARCHAR(11) NOT NULL,
MUSTERIADRES INT,
PRIMARY KEY CLUSTERED
(
MUSTERIID ASC
)
WITH(PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]
)ON [PRIMARY]



/*-------------------------------------------------FOREIGN KEY--------------------------------------------------------*/

ALTER TABLE ADRES WITH CHECK ADD CONSTRAINT [FK_ADRESMUSTERI] FOREIGN KEY(MUSTERIID) REFERENCES MUSTERILER (MUSTERIID) 
ALTER TABLE ADRES CHECK CONSTRAINT [FK_ADRESMUSTERI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISMUSTERI] FOREIGN KEY(MUSTERIID) REFERENCES MUSTERILER (MUSTERIID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISMUSTERI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISSATICI] FOREIGN KEY(SATICIID) REFERENCES SATICI(SATICIID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISSATICI]

ALTER TABLE SIPARIS WITH CHECK ADD CONSTRAINT [FK_SIPARISURUN] FOREIGN KEY(URUNID) REFERENCES URUN(URUNID)
ALTER TABLE SIPARIS CHECK CONSTRAINT [FK_SIPARISURUN]

/*-------------------------------------------------FOREIGN KEY--------------------------------------------------------*/





/**/

SELECT * FROM MUSTERILER

INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('AHMET','KAVUS','E','5326151745')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('SEFA','KALYA','E','5326151544')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('SERDAR','KAVUS','E','5326856974')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('EMRAH','KAVUS','E','5326568445')
INSERT INTO MUSTERILER(MUSTERIAD,MUSTERISOYAD,MUSTERICINSIYET,MUSTERITELEFON)VALUES ('EDA','GULER','K','5326158854')




SELECT * FROM ADRES

INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (1,'TURKIYE','ISTANBUL','PENDIK','EV ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (1,'TURKIYE','ISTANBUL','TUZLA','IS ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (2,'TURKIYE','IZMIR','KORDON','EV ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (3,'TURKIYE','ÇORUM','OSMANCIK','IS ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (4,'TURKIYE','ERZINCAN','MERKEZ','EV ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (5,'TURKIYE','TRAPZON','SURMENE','EV ADRESI')
INSERT INTO ADRES(MusterýID,ADRESULKE,ADRESIL,ADRESILCE,ADRESYORUM) VALUES (5,'AMERIKA','PENSILVANYA','PITTSBURG','IS ADRESI')


SELECT * FROM SATICI

INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('MUSLUM','GURSES','5437645589')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('IBRAHIM','TATLISES','2164567894')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('ZEKI','MUREN','123456789')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('MUHAMMED','ARSLAN','42315648')
INSERT INTO SATICI(SATICIADI,SATICISOYADI,SATICITELEFON) VALUES ('ORHAN','ADNAN','5469875326')

SELECT * FROM URUN

INSERT INTO URUN(URUNKODU,URUNADI,URUNFÝYATI) VALUES ('456','BUZDOLABI','788')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFÝYATI) VALUES ('8546','TELEFON','1500')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFÝYATI) VALUES ('36987','KLIMA','999')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFÝYATI) VALUES ('2233','CAMASIR MAKINASI','659')
INSERT INTO URUN(URUNKODU,URUNADI,URUNFÝYATI) VALUES ('2369','BULASIK MAKINASI','3900')


ALTER TABLE SIPARIS ALTER COLUMN SIPARISTARIH VARCHAR(20)

SELECT * FROM SIPARIS

INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (2,'17_08_2020','KARGODA',3,5)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (1,'15_10_2020','KARGODA',4,1)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (4,'17_08_2020','KARGODA',1,2)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (1,'17_08_2020','KARGODA',2,1)
INSERT INTO SIPARIS(MUSTERIID,SIPARISTARIH,SIPARISDURUM,URUNID,SATICIID) VALUES (3,'17_08_2020','KARGODA',5,3)



/*
DROP TABLE SIPARIS
DELETE FROM SIPARIS
TRUNCATE TABLE SIPARIS
UPDATE MUSTERILER SET MUSTERICINSIYET='K' WHERE MUSTERIAD='SERDAR'
*/



SELECT DISTINCT MUSTERILER.MUSTERIAD+' '+MUSTERILER.MUSTERISOYAD [AD SOYAD], 
ADRES.ADRESULKE+' '+ADRES.ADRESIL+' '+ADRES.ADRESILCE+' '+ADRES.ADRESYORUM [AÇIK ADRES],
URUN.URUNADI [SÝPARÝÞ EDÝLEN ÜRÜN], SIPARIS.SIPARISTARIH [SÝPARÝÞ TARÝHÝ], SIPARIS.SIPARISDURUM [ÜRÜN DURUMU], SATICI.SATICIADI+' '+SATICI.SATICISOYADI [ÜRÜN SATICISI] FROM MUSTERILER 
INNER JOIN SIPARIS ON MUSTERILER.MUSTERIID = SIPARIS.MUSTERIID
INNER JOIN ADRES ON ADRES.MusterýID=MUSTERILER.MUSTERIID
INNER JOIN URUN ON URUN.URUNID=SIPARIS.URUNID
INNER JOIN SATICI ON SATICI.SATICIID=SIPARIS.SATICIID
